version: 0.1
http:
  addr: 0.0.0.0:443
  tls:
    certificate: /ssl-certs/fullchain.pem
    key: /ssl-certs/privkey.pem
storage:
  s3:
    region: eu-central-1
redis:
  addr: registry-cache:6379
auth:
  htpasswd:
    realm: Quentin Burgniard Registry
    path: /registry-password/htpasswd
log:
  level: error