version: 0.1
http:
  addr: localhost:443
  tls:
    certificate: /ssl-certs/live/d/fullchain.pem
    key: /ssl-certs/live/d/privkey.pem
storage:
  s3:
    bucket: registry.quentinburgniard.com
    region: eu-central-1
redis:
  addr: registry-cache:6379
auth:
  htpasswd:
    realm: Quentin Burgniard Registry
    path: /registry-password/htpasswd
log:
  level: error