language: shell

services: docker

branches: master

env:
  - API_VERSION=0.1
  - CLOUD_VERSION=0.1
  - CV_VERSION=1.0
  - DISCOVER_ME_VERSION=1.0
  - DISCOVER_ME_API_VERSION=1.0
  - ENV=dev
  - LAVOIEDUCOEUR_VERSION=1.0
  - PORTFOLIO_VERSION=2.0
  - REVERSE_PROXY_VERSION=1.1

install: docker-compose up reverse-proxy

script:
  - docker ps

deploy:	
  provider: script	
  script:
#    - ssh -t $CI_USER@$CI_HOST "git pull ${CI_DIRECTORY} && docker ps"
    - echo deploy

addons:
  ssh_known_hosts: digital-leman.com
# hosts: digital-leman.com

notifications:
  slack:
    secure: "HGLqnhgU91mcOH1MvsaJcwNsrUFQY+f6YPJj37hyTLPPNryBoFK2AS8/cIkxp2gvycHvaJSY56Qd4vmxtLYHKkjJe6cOMs/XT9Yh3BscQhsnP7UtGPn/QYUxDZF8IybFHViLvxg2nnq2ZcP8jcEgdnuG0ezMB617wheup7y6GskMhCiN/TyuoZJ+KoDoVQnI5jVlHuTEiLToe/ZAtdSlVJgKAYgOk3WdcIJ08tkKplMc81zWYkewxaLA1HUb8lpG3a0/CBQ+qXc0dLLqrgj81oLAPvRvVXiAwz9jg/gKC3EltMAL5f+oGqz3iQucYJTkve2Y0xEwtL/FsPVPk3rBXrkj8gBu32MSAU7gN1/b49ORBYVErmCJ6oKjpiFc24DSSxZnfK703/mNHPtHyDgwQ5hfLTF3vOj0lhnzGYgB90jQS9JVX155cYu3TDXQldcGU/OmrldCG/0djLbWaTK7GCZdrTz4xM1V3PT7UUEFmmI0DmRYHwxHpoSuouyAFG62H2CO/JZ0zEK9UpSlAeD+PBGBbaZGlTJY8b/Y+NmvzKhY84gvSzj0rTfBcdSslOusHaHlu+CfIYbd/Zf1YWW2TxGDFREd38t4qYHX5e8gJTLVP50v63sYy2w7IDXxpnqv08iP/yIVNl58XiFyr2SkB1ZUJtfDoFqkAWSkbnpMfWU="