language: shell

services: docker

branches: master

install: echo install

deploy:
  provider: script
  script: echo deploy

# after_success:
#   - echo success

# after_failure:
#   - echo failure

# env:
#   - DB=mongodb
#   - DB=redis
#   - DB=mysqlenv:
#  global:
#    - FOO: foo
#    jobs:
#    - FOO: foo

# jobs:
#   include:
#   - stage: test
#   script: docker --version
#   name: "Unit Tests"
#   - stage: deploy
#   script: docker ps

# deploy:
#   provider: script
#   script: docker ps

# #branches:
# #  only: master
# jobs:

# addons:
#   ssh_known_hosts: digital-leman.com
#   hosts: digital-leman.com