language: shell

services: docker

branches: master

before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .travis/env.enc -out .env -d
  - openssl aes-256-cbc -K $encrypted_6d021eaab8d3_key -iv $encrypted_6d021eaab8d3_iv -in .travis/deploy.enc -out .travis/deploy -d
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

install:
  - docker-compose up -d

script:
  - docker ps

deploy:	
  provider: script
  script: bash .travis/deploy.sh

addons:
  ssh_known_hosts:
    - digital-leman.com

notifications:
  slack: $SLACK_TOKEN