language: shell

services: docker

branches: master

before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .travis/.env.enc -out .env -d
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

install:
  - docker-compose up -d reverse-proxy

script:
  - docker ps

deploy:	
  provider: script
  script: bash ci-deploy.sh
  skip_cleanup: true

addons:
  ssh_known_hosts:
    - digital-leman.com

notifications:
  slack: $SLACK_TOKEN