language: shell

services: docker

branches: master

env: |
  API_VERSION=0.1
  CLOUD_VERSION=0.1
  CV_VERSION=1.0
  DISCOVER_ME_VERSION=1.0
  DISCOVER_ME_API_VERSION=1.0
  ENV=dev
  LAVOIEDUCOEUR_VERSION=1.0
  PORTFOLIO_VERSION=2.0
  REVERSE_PROXY_VERSION=1.1

before_install:
  - openssl aes-256-cbc -K $encrypted_6d021eaab8d3_key -iv $encrypted_6d021eaab8d3_iv -in .travis/deploy.pem.enc -out .travis/deploy.pem -d
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY

install:
  - docker-compose up -d registry
  - docker-compose up -d reverse-proxy

script:
  - docker ps

deploy:	
  provider: script
  script:
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/deploy.pem
    - ssh-add .travis/deploy.pem
    #- ssh -t $USER@$REGISTRY "git pull ${CI_DIRECTORY} && docker-compose --project-directory ${CI_DIRECTORY} up -d registry"
    - ssh -t $USER@$REVERSE_PROXY "git pull ${CI_DIRECTORY} && docker-compose --project-directory ${CI_DIRECTORY} up -d reverse-proxy"

addons:
  ssh_known_hosts:
    - $REGISTRY
    - $REVERSE_PROXY

notifications:
  slack: $SLACK_TOKEN