language: shell

services: docker

branches: master

env: |
  API_VERSION=0.1
  CLOUD_VERSION=0.1
  CV_VERSION=1.0
  DISCOVER_ME_VERSION=1.0
  DISCOVER_ME_API_VERSION=1.0
  ENV=dev
  LAVOIEDUCOEUR_VERSION=1.0
  PORTFOLIO_VERSION=2.0
  REVERSE_PROXY_VERSION=1.1

before_install:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

install: docker-compose up -d reverse-proxy

script:
  - docker ps

deploy:	
  provider: script	
  script:
#    - ssh -t $CI_USER@$CI_HOST "git pull ${CI_DIRECTORY} && docker ps"
    - echo deploy

addons:
  ssh_known_hosts: digital-leman.com
# hosts: digital-leman.com

notifications:
  slack: $SLACK_TOKEN