language: shell

services: docker

branches: master

before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .travis/env.enc -out .env -d
  - openssl aes-256-cbc -K $encrypted_6d021eaab8d3_key -iv $encrypted_6d021eaab8d3_iv -in .travis/deploy.enc -out .travis/deploy -d
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY

install:
  - docker-compose up -d registry
  - docker-compose up -d reverse-proxy

script:
  - docker ps

deploy:	
  provider: script
  script:
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/deploy
    - ssh-add .travis/deploy
    #- ssh -t $USER@$REGISTRY "git pull ${DIRECTORY} && docker-compose --project-directory ${DIRECTORY} up -d registry"
    - ssh -t $USER@$MAIN_DOMAIN "git pull ${DIRECTORY} && docker-compose --project-directory ${DIRECTORY} up -d reverse-proxy"

addons:
  ssh_known_hosts:
    - $REGISTRY
    - $MAIN_DOMAIN

notifications:
  slack: $SLACK_TOKEN