version: "3"

services:
  api:
    container_name: api
    image: strapi/strapi
    environment:
      APP_NAME: api
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongodb
      DATABASE_NAME: api
      DATABASE_USERNAME: $MONGO_ROOT_USER
      DATABASE_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - strapi:/usr/src/api/strapi
    depends_on:
      - mongodb
    restart: always

  cloud:
    container_name: cloud
    image: nextcloud
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: cloud
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      NEXTCLOUD_ADMIN_USER: $NEXTCLOUD_ADMIN_USER
      NEXTCLOUD_ADMIN_PASSWORD: $NEXTCLOUD_ADMIN_PASSWORD
      SMTP_HOST: $SMTP_HOST
      SMTP_SECURE: $SMTP_SECURE
      SMTP_PORT: $SMTP_PORT
      SMTP_NAME: $SMTP_NAME
      SMTP_PASSWORD: $SMTP_PASSWORD
    restart: always
    
  cv:
    container_name: cv
    image: ${DOCKER_REGISTRY}/cv:${CV_VERSION}
    restart: always

  discover-me:
    container_name: discover-me
    image: ${DOCKER_REGISTRY}/discover-me:${DISCOVER_ME_VERSION}
    restart: always

  discover-me-api:
    container_name: discover-me-api
    image: ${DOCKER_REGISTRY}/discover-me-api:${DISCOVER_ME_API_VERSION}
    restart: always
    
  lavoieducoeur:
    container_name: lavoieducoeur
    image: ${DOCKER_REGISTRY}/la-voie-du-coeur:${LAVOIEDUCOEUR_VERSION}
    depends_on:
      - api
    restart: always

  letsencrypt-certificate:
    container_name: letsencrypt-certificate
    image: certbot/dns-digitalocean
    command: certonly --dns-digitalocean --dns-digitalocean-credentials /digitalocean.ini --dns-digitalocean-propagation-seconds 60 -n --agree-tos -m quentinburgniard@gmail.com -d $DOMAIN_NAME
    volumes:
      - certs:/etc/letsencrypt
      - ./letsencrypt-dns-challenge/digitalocean.ini:/etc/digitalocean.ini:ro

  mariadb:
    container_name: mariadb
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: cloud
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: api
    volumes:
      - mongodb:/data/db
    restart: always
      
  portfolio:
    container_name: portfolio
    image: ${DOCKER_REGISTRY}/portfolio:${PORTFOLIO_VERSION}
    restart: always
    
  registry:
    container_name: registry
    image: registry:2
    environment:
      REGISTRY_STORAGE_S3_BUCKET: $DOCKER_REGISTRY
      REGISTRY_STORAGE_S3_ACCESSKEY: $AWS_API_ACCESSKEY
      REGISTRY_STORAGE_S3_SECRETKEY: $AWS_API_SECRETKEY
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - ./registry/htpasswd:/auth/htpasswd:ro
      - certs:/etc/letsencrypt:ro
    ports:
      - "443:443"
    depends_on:
      - letsencrypt-certificate
      - registry-htpasswd
    restart: always
    
  registry-htpasswd:
    container_name: registry-htpasswd
    image: registry:2
    entrypoint: htpasswd
    command: -bcB -C 17 /auth/htpasswd $DOCKER_REGISTRY_USER $DOCKER_REGISTRY_PASSWORD
    volumes:
      - ./registry:/auth

  reverse-proxy:
    container_name: reverse-proxy
    image: ${DOCKER_REGISTRY}/reverse-proxy:${REVERSE_PROXY_VERSION}
    environment:
      API_KEY: $AMPLIFY_API_KEY
      AMPLIFY_IMAGENAME: $AMPLIFY_IMAGENAME
    volumes:
      - certs:/certs:ro
      - ./reverse-proxy/${ENV}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/conf.d:/etc/nginx/conf.d:ro
    ports:
      - $HTTP
      - $HTTPS
    depends_on:
      - letsencrypt-certificate
      - api
      - cloud
      - cv
      - discover-me
      - discover-me-api
      - portfolio

volumes:
  certs:
  mariadb:
  mongodb:
  strapi:
