version: "3"

services:
  api:
    container_name: api
    image: strapi/strapi
    environment:
      APP_NAME: api
      DATABASE_CLIENT: mongo
      DATABASE_HOST: api-db
      DATABASE_NAME: api
      DATABASE_USERNAME: $API_DB_USER
      DATABASE_PASSWORD: $API_DB_PASSWORD
    volumes:
      - api:/usr/src/api/strapi
    depends_on:
      - api-db
    restart: always

  api-db:
    container_name: api-db
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: $API_DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $API_DB_PASSWORD
      MONGO_INITDB_DATABASE: api
    volumes:
      - api-db:/data/db
    restart: always

  cloud:
    container_name: cloud
    image: nextcloud:18
    environment:
      NEXTCLOUD_ADMIN_USER: $CLOUD_USER
      NEXTCLOUD_ADMIN_PASSWORD: $CLOUD_PASSWORD
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.quentinburgniard.fr
      MYSQL_HOST: cloud-db
      MYSQL_DATABASE: cloud
      MYSQL_USER: $CLOUD_DB_USER
      MYSQL_PASSWORD: $CLOUD_DB_PASSWORD
    depends_on:
      - cloud-db
    restart: always

  cloud-db:
    container_name: cloud-db  
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: $CLOUD_DB_USER
      MYSQL_PASSWORD: $CLOUD_DB_PASSWORD
      MYSQL_DATABASE: cloud
    volumes:
      - cloud-db:/var/lib/mysql
    restart: always
    
  cv:
    container_name: cv
    image: ${DOCKER_REGISTRY}/cv:${CV_VERSION}
    restart: always

  discover-me:
    container_name: discover-me
    image: ${DOCKER_REGISTRY}/discover-me:${DISCOVER_ME_VERSION}
    depends_on:
      - discover-me-api
    restart: always

  discover-me-api:
    container_name: discover-me-api
    image: ${DOCKER_REGISTRY}/discover-me-api:${DISCOVER_ME_API_VERSION}
    restart: always
    
  lavoieducoeur:
    container_name: lavoieducoeur
    image: ${DOCKER_REGISTRY}/la-voie-du-coeur:${LAVOIEDUCOEUR_VERSION}
    depends_on:
      - api
    restart: always

  portfolio:
    container_name: portfolio
    image: ${DOCKER_REGISTRY}/portfolio:${PORTFOLIO_VERSION}
    restart: always

  registry:
    container_name: registry
    image: registry:2
    environment:
      REGISTRY_STORAGE_S3_BUCKET: $DOCKER_REGISTRY
      REGISTRY_STORAGE_S3_ACCESSKEY: $AWS_API_ACCESSKEY
      REGISTRY_STORAGE_S3_SECRETKEY: $AWS_API_SECRETKEY
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - registry-password:/registry-password:ro
      - ssl-certs:/ssl-certs:ro
    ports:
      - 443:443
    depends_on:
      - registry-cache
      - ssl-certs-${ENV}
      - registry-password
    restart: always
  
  registry-cache:
    container_name: registry-cache
    image: redis:5
    restart: always
      
  registry-password:
    container_name: registry-password
    image: registry:2
    entrypoint: htpasswd
    command: -bcB -C 17 /registry-password/htpasswd $DOCKER_REGISTRY_USER $DOCKER_REGISTRY_PASSWORD
    volumes:
      - registry-password:/registry-password/htpasswd
  
  reverse-proxy:
    container_name: reverse-proxy
    image: ${DOCKER_REGISTRY}/reverse-proxy:${REVERSE_PROXY_VERSION}
    environment:
      API_KEY: $AMPLIFY_API_KEY
      AMPLIFY_IMAGENAME: $AMPLIFY_IMAGENAME
    volumes:
      - ssl-certs:/ssl-certs:ro
      - ./reverse-proxy:/etc/nginx:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - cloud
      - cv
      - discover-me
      - portfolio
      - ssl-certs-${ENV}
  
  ssl-certs-dev:
    container_name: ssl-certs-dev
    image: frapsoft/openssl
    command: req -keyout /ssl-certs/privkey.pem -newkey rsa:2048 -nodes -out /ssl-certs/fullchain.pem -subj "/C=CH/ST=Geneve/L=Geneve/O=Digital Leman/CN=digital-leman.com" -x509
    volumes:
      - ssl-certs:/ssl-certs

  ssl-certs-prod:
    container_name: ssl-certs-prod
    image: certbot/dns-digitalocean
    command: certonly --dns-digitalocean --dns-digitalocean-credentials /digitalocean.ini --dns-digitalocean-propagation-seconds 60 -n --agree-tos -m quentinburgniard@gmail.com -d $MAIN_DOMAIN -d $DOMAINS
    volumes:
      - ssl-certs:/etc/letsencrypt/live/${MAIN_DOMAIN}
      - ./letsencrypt-dns-challenge/digitalocean.ini:/etc/digitalocean.ini:ro

volumes:
  api-db:
  cloud-db:
  registry-password:
  ssl-certs:
  api: