version: '3'

services:

  reverse-proxy:
    container_name: reverse-proxy
    image: quentinburgniard/reverse-proxy
    environment:
      API_KEY: $AMPLIFY_API_KEY
      AMPLIFY_IMAGENAME: $AMPLIFY_IMAGENAME
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - ./reverse-proxy/${ENV}/:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - phpmyadmin
      - api
    restart: always

  db:
    container_name: db
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: api
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: $MYSQL_ROOT_PASSWORD
      PHPMYADMIN_URI: https://sql.quentinburgniard.com
    depends_on:
      - db
    restart: always

  api:
    container_name: api-${API_VERSION}
    image: quentinburgniard/api:${API_VERSION}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: api
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_CONFIG_EXTRA: "define( 'WP_POST_REVISIONS', 5 ); define( 'WP_AUTO_UPDATE_CORE', true );"
    volumes:
      - wp:/var/www/html
    depends_on:
      - db
    restart: always

  portfolio:
    container_name: portfolio-${PORTFOLIO_VERSION}
    image: quentinburgniard/portfolio:${PORTFOLIO_VERSION}
    restart: always

  cv:
    container_name: cv-${CV_VERSION}
    image: quentinburgniard/cv:${CV_VERSION}
    restart: always

  discover-me:
    container_name: discover-me-${DISCOVER_ME_VERSION}
    image: quentinburgniard/discover-me:${DISCOVER_ME_VERSION}
    restart: always

  discover-me-api:
    container_name: discover-me-api-${DISCOVER_ME_API_VERSION}
    image: quentinburgniard/discover-me-api:${DISCOVER_ME_API_VERSION}
    restart: always

volumes:
  letsencrypt:
  mysql:
  wp: