version: '3'

services:

  registry:
    container_name: registry
    image: registry:2
    environment:
      REGISTRY_STORAGE_S3_ACCESSKEY: $AWS_API_ACCESSKEY
      REGISTRY_STORAGE_S3_SECRETKEY: $AWS_API_SECRETKEY
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml
    ports:
      - 5000:5000
    restart: always

  letsencrypt-dns-challenge:
      container_name: letsencrypt-dns-challenge
      image: certbot/dns-digitalocean
      command: certonly --dns-digitalocean --dns-digitalocean-credentials /digitalocean.ini --dns-digitalocean-propagation-seconds 60 -n --agree-tos -m quentinburgniard@gmail.com -d digital-leman.com,quentinburgniard.com,quentinburgniard.fr,*.digital-leman.com,*.quentinburgniard.com,*.quentinburgniard.fr
      volumes:
        - letsencrypt:/etc/letsencrypt
        - ./letsencrypt-dns-challenge/digitalocean.ini:/digitalocean.ini:ro

volumes:
  auth:
  letsencrypt:
  