version: "3.7"

services:
  api:
    container_name: api
    image: quentinburgniard/api:3.0.4
    environment:
      ADMIN_TOKEN: $API_ADMIN_TOKEN
      AWS_USER: $AWS_USER
      AWS_PASSWORD: $AWS_PASSWORD
      DATA_SERVICE: api-data
      DATA_USER: $API_DATA_USER
      DATA_PASSWORD: $API_DATA_PASSWORD
      USER_TOKEN: $API_USER_TOKEN
    volumes:
      - api:/usr/src/api/strapi
    depends_on:
      - api-data
    restart: always

  api-data:
    container_name: api-data
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: $API_DATA_USER
      MONGO_INITDB_ROOT_PASSWORD: $API_DATA_PASSWORD
      MONGO_INITDB_DATABASE: api
    volumes:
      - api-data:/data/db
    restart: always

  cloud:
    container_name: cloud
    image: quentinburgniard/cloud:0.0.9
    environment:
      NEXTCLOUD_ADMIN_USER: $CLOUD_USER
      NEXTCLOUD_ADMIN_PASSWORD: $CLOUD_PASSWORD
      NEXTCLOUD_TRUSTED_DOMAINS: cloud
      MYSQL_HOST: cloud-data
      MYSQL_DATABASE: cloud
      MYSQL_USER: $CLOUD_DATA_USER
      MYSQL_PASSWORD: $CLOUD_DATA_PASSWORD
      REDIS_HOST: cloud-cache
    volumes:
      - cloud:/var/www/html
    depends_on:
      - cloud-data
      - cloud-cache
    restart: always

  cloud-data:
    container_name: cloud-data
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: $CLOUD_DATA_USER
      MYSQL_PASSWORD: $CLOUD_DATA_PASSWORD
      MYSQL_DATABASE: cloud
    volumes:
      - cloud-data:/var/lib/mysql
    restart: always

  cloud-cache:
    container_name: cloud-cache
    image: redis:5
    restart: always
    
  cv:
    container_name: cv
    image: quentinburgniard/cv:2.0.0
    restart: always

  discover-me:
    container_name: discover-me
    image: quentinburgniard/discover-me:1
    depends_on:
      - discover-me-data
    restart: always

  discover-me-data:
    container_name: discover-me-data
    image: quentinburgniard/discover-me-data:1
    restart: always
    
  hestia:
    container_name: hestia
    image: quentinburgniard/hestia:0.0.5
    restart: always

  invoice-generator:
    container_name: invoice-generator
    image: quentinburgniard/invoice-generator:1.0.2
    restart: always
    
  lavoieducoeur:
    container_name: lavoieducoeur
    image: quentinburgniard/lavoieducoeur:1
    depends_on:
      - api
    restart: always

  portfolio:
    container_name: portfolio
    image: quentinburgniard/portfolio:2.0.4
    depends_on:
      - search
    restart: always
  
  reverse-proxy:
    container_name: reverse-proxy
    image: quentinburgniard/reverse-proxy:1
    environment:
      AMPLIFY_IMAGENAME: $AMPLIFY
    volumes:
      - ssl-certs:/ssl-certs:ro
      - ./reverse-proxy:/etc/nginx:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - cloud
      - cv
      - discover-me
      - hestia
      - invoice-generator
      - lavoieducoeur
      - portfolio
    restart: always

  search:
    container_name: search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - discovery.type=single-node
    volumes:
      - search:/usr/share/elasticsearch/data
    restart: always
  
  ssl-certs-dev:
    container_name: ssl-certs-dev
    image: quentinburgniard/ssl-certs-dev:1.1.0
    command: req -keyout /ssl-certs/live/d/privkey.pem -newkey rsa:2048 -nodes -out /ssl-certs/live/d/fullchain.pem -subj "/C=CH/ST=Geneve/L=Geneve/O=Digital Leman/CN=digital-leman.com" -x509
    volumes:
      - ssl-certs:/ssl-certs

  ssl-certs-prod:
    container_name: ssl-certs-prod
    image: certbot/dns-digitalocean
    command: certonly --dns-digitalocean --dns-digitalocean-credentials /digitalocean.ini --dns-digitalocean-propagation-seconds 600 -n --agree-tos -m quentinburgniard@gmail.com --cert-name d -d $DOMAINS
    volumes:
      - ssl-certs:/etc/letsencrypt
      - ./ssl-certs/digitalocean.ini:/digitalocean.ini:ro

volumes:
  api-data:
  cloud:
  cloud-data:
  registry-password:
  search:
  ssl-certs:
  api: