version: '3'

services:

  reverse-proxy:
    container_name: reverse-proxy
    image: quentinburgniard/reverse-proxy
    environment:
      API_KEY: $AMPLIFY_API_KEY
      AMPLIFY_IMAGENAME: $AMPLIFY_IMAGENAME
    volumes:
      - certs:/certs:ro
      - ./reverse-proxy/${ENV}:/etc/nginx:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - phpmyadmin
      - api
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MYSQL_DATABASE: api
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf:ro
    restart: always

  mongo:
    container_name: mongodb
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGODB_ROOT_USER
      MONGODB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: api

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PHPMYADMIN_URI: $PHPMYADMIN_URI
    depends_on:
      - mariadb
    restart: always

  api:
    container_name: api-${API_VERSION}
    image: quentinburgniard/api:${API_VERSION}
    environment:
      APP_NAME: strapi
      DATABASE_CLIENT: MongoDB
      DATABASE_HOST: mongodb
      DATABASE_NAME: api
      DATABASE_USERNAME: $MONGODB_ROOT_USER
      DATABASE_PASSWORD: $MONGODB_ROOT_PASSWORD
    volumes:
      - strapi:/usr/src/api/strapi
    depends_on:
      - mongo
    restart: always

  portfolio:
    container_name: portfolio-${PORTFOLIO_VERSION}
    image: quentinburgniard/portfolio:${PORTFOLIO_VERSION}
    depends_on:
      - mariadb
    restart: always

  cv:
    container_name: cv-${CV_VERSION}
    image: quentinburgniard/cv:${CV_VERSION}
    restart: always

  discover-me:
    container_name: discover-me-${DISCOVER_ME_VERSION}
    image: quentinburgniard/discover-me:${DISCOVER_ME_VERSION}
    restart: always

  discover-me-api:
    container_name: discover-me-api-${DISCOVER_ME_API_VERSION}
    image: quentinburgniard/discover-me-api:${DISCOVER_ME_API_VERSION}
    restart: always

volumes:
  certs:
  mysql:
  strapi: