version: 0.1
log:
  level: error
storage:
  s3:
    region: us-east-1
    bucket: registry.quentinburgniard.com
auth:
  htpasswd:
    realm: Quentin Burgniard Registry
    path: /auth/htpasswd
http:
  addr: 0.0.0.0:443
  tls:
    certificate: /etc/letsencrypt/live/registry.quentinburgniard.com/fullchain.pem
    key: /etc/letsencrypt/live/registry.quentinburgniard.com/privkey.pem
